spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: draw-system-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-epjf3l5h.sql.tencentcdb.com:27006/draw?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1187246802zqZQ
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.drawsystemserver.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8080
# 文件存储路径
file:
  upload-dir: uploads